// activitiesData.js
const activitiesData = [
  // 🏃 Cardio & Endurance
  { name: "Running (jog)", met: 7 },
  { name: "Running (fast)", met: 11 },
  { name: "Running on Treadmill", met: 8 },
  { name: "Walking (casual)", met: 3.5 },
  { name: "Walking (brisk)", met: 4.5 },
  { name: "Hiking", met: 6 },
  { name: "Treadmill Walking", met: 4 },
  { name: "Cycling (casual)", met: 4 },
  { name: "Cycling (fast)", met: 8 },
  { name: "Stationary Bike (light)", met: 3.5 },
  { name: "Stationary Bike (vigorous)", met: 7 },
  { name: "Rowing (light)", met: 4 },
  { name: "Rowing (vigorous)", met: 7 },
  { name: "Swimming (casual)", met: 4 },
  { name: "Swimming (vigorous)", met: 8 },
  { name: "Jump Rope", met: 12 },
  { name: "Dance (Zumba)", met: 6 },
  { name: "Dance (Hip Hop)", met: 5.5 },
  { name: "Dance (Ballet)", met: 3.5 },
  { name: "Elliptical Trainer", met: 5.5 },
  { name: "Stair Climbing", met: 6 },
  { name: "Step Aerobics (low impact)", met: 4.5 },
  { name: "Step Aerobics (high impact)", met: 6 },
  { name: "Sprinting Intervals", met: 14 },
  { name: "Trail Running", met: 9 },

  // 🏋️ Strength & Resistance
  { name: "Weightlifting (light)", met: 3 },
  { name: "Weightlifting (heavy)", met: 6 },
  { name: "Push-ups", met: 8 },
  { name: "Pull-ups", met: 8 },
  { name: "Squats", met: 5 },
  { name: "Jump Squats", met: 8 },
  { name: "Lunges", met: 5 },
  { name: "Burpees", met: 10 },
  { name: "Deadlifts", met: 6 },
  { name: "Bench Press", met: 6 },
  { name: "Shoulder Press", met: 5 },
  { name: "Bicep Curls", met: 3 },
  { name: "Tricep Dips", met: 4 },
  { name: "Kettlebell Training", met: 6 },
  { name: "Medicine Ball Workout", met: 5 },
  { name: "Resistance Band Training", met: 5 },
  { name: "CrossFit", met: 10 },
  { name: "Bodyweight Training", met: 6 },
  { name: "Calisthenics", met: 6 },
  { name: "Powerlifting", met: 6.5 },
  { name: "Olympic Lifting", met: 7 },

  // 🧘 Flexibility, Mind & Balance
  { name: "Yoga (Hatha)", met: 2.5 },
  { name: "Yoga (Power)", met: 3.5 },
  { name: "Yoga (Vinyasa)", met: 3.5 },
  { name: "Yoga (Restorative)", met: 2 },
  { name: "Pilates", met: 3 },
  { name: "Stretching", met: 2 },
  { name: "Foam Rolling", met: 1.5 },
  { name: "Tai Chi", met: 3 },
  { name: "Breathing Exercises", met: 1 },
  { name: "Balance Board Training", met: 3 },
  { name: "Gymnastics", met: 5 },

  // 🎾 Sports & Games
  { name: "Badminton", met: 5 },
  { name: "Tennis (singles)", met: 7 },
  { name: "Tennis (doubles)", met: 5 },
  { name: "Basketball (casual)", met: 6 },
  { name: "Basketball (game)", met: 8 },
  { name: "Football/Soccer (casual)", met: 6 },
  { name: "Football/Soccer (game)", met: 10 },
  { name: "Table Tennis", met: 4 },
  { name: "Volleyball (casual)", met: 3.5 },
  { name: "Volleyball (beach)", met: 5 },
  { name: "Boxing (sparring)", met: 8 },
  { name: "Boxing (heavy bag)", met: 7 },
  { name: "Kickboxing", met: 10 },
  { name: "Wrestling", met: 9 },
  { name: "Martial Arts (Karate)", met: 8 },
  { name: "Martial Arts (Taekwondo)", met: 8 },
  { name: "Judo", met: 8 },
  { name: "Fencing", met: 6 },
  { name: "Cricket", met: 5 },
  { name: "Rugby", met: 9 },
  { name: "Hockey", met: 7 },
  { name: "Lacrosse", met: 9 },
  { name: "Golf (walking)", met: 4 },
  { name: "Golf (with cart)", met: 2.5 },
  { name: "Bowling", met: 3 },
  { name: "Skateboarding", met: 4 },
  { name: "Rollerblading", met: 5 },
  { name: "Ice Skating", met: 5 },
  { name: "Skiing (downhill)", met: 7 },
  { name: "Skiing (cross-country)", met: 8 },
  { name: "Snowboarding", met: 6.5 },
  { name: "Surfing", met: 4.5 },
  { name: "Kayaking", met: 5 },
  { name: "Canoeing", met: 4.5 },
  { name: "Rowing (outdoor)", met: 7 },
  { name: "Climbing (rock)", met: 7 },
  { name: "Climbing (bouldering)", met: 6 },
  { name: "Paddle", met: 8 },
  { name: "Archery", met: 2.5 },
  { name: "Horseback Riding", met: 4.5 },
  { name: "Ultimate Frisbee", met: 8 },

  // 🏡 Lifestyle & Daily Activities
  { name: "House Cleaning", met: 3 },
  { name: "Vacuuming", met: 2.5 },
  { name: "Mopping Floors", met: 3 },
  { name: "Washing Dishes", met: 2 },
  { name: "Laundry (folding/ironing)", met: 2 },
  { name: "Gardening (light)", met: 3 },
  { name: "Gardening (digging)", met: 5 },
  { name: "Carrying Groceries", met: 3 },
  { name: "Cooking", met: 2 },
  { name: "Playing with Kids", met: 3 },
  { name: "Walking the Dog", met: 2.5 },
  { name: "Shoveling Snow", met: 6 },
  { name: "Washing Car", met: 3.5 },
  { name: "Yard Work", met: 4 },
  { name: "Moving Furniture", met: 6 },
  { name: "Climbing Stairs", met: 8 },
  { name: "Carpentry/DIY", met: 4 },
];

export default activitiesData;
