const recipesData = {
  // Categories
  Categories: ["Breakfast", "Lunch", "Dinner", "Vegan", "Sugar Free"],

Favorites: [
    {
      id: 101,
      title: "Peanut Butter Banana Shake",
      calories: 402,
      time: 5,
      image: "https://via.placeholder.com/300",
      ingredients: [
        "1 banana",
        "2 tbsp peanut butter",
        "1 cup milk (or almond milk)",
        "1 tsp honey",
        "Ice cubes",
      ],
      instructions: [
        "Peel and slice the banana.",
        "Add banana, peanut butter, milk, and honey into a blender.",
        "Blend until smooth.",
        "Add ice cubes and blend again until frothy.",
        "Serve chilled.",
      ],
      nutrition: {
        protein: "12g",
        carbs: "45g",
        fat: "15g",
      },
    },
    {
      id: 102,
      title: "Mint Chocolate Shake",
      calories: 232,
      time: 3,
      image: "https://via.placeholder.com/300",
      ingredients: [
        "1 cup milk",
        "2 tbsp cocoa powder",
        "1 tbsp sugar or honey",
        "Fresh mint leaves",
        "Ice cubes",
      ],
      instructions: [
        "Blend milk, cocoa powder, and sugar until smooth.",
        "Add mint leaves and ice cubes.",
        "Blend again until creamy.",
        "Pour into a glass and garnish with mint.",
      ],
      nutrition: {
        protein: "8g",
        carbs: "28g",
        fat: "7g",
      },
    },
    {
      id: 103,
      title: "Green Spinach Smoothie",
      calories: 273,
      time: 5,
      image: "https://via.placeholder.com/300",
      ingredients: [
        "1 cup spinach leaves",
        "1 banana",
        "1/2 cup Greek yogurt",
        "1 cup almond milk",
        "1 tsp chia seeds",
      ],
      instructions: [
        "Wash spinach leaves thoroughly.",
        "Add spinach, banana, yogurt, almond milk, and chia seeds to blender.",
        "Blend until smooth and creamy.",
        "Serve immediately.",
      ],
      nutrition: {
        protein: "10g",
        carbs: "35g",
        fat: "8g",
      },
    },
  ],

  // Breakfast
  Breakfast: [
    {
      id: 101,
      title: "Avocado Toast",
      calories: "320 kcal",
      carbs: 28,
      fats: 14,
      protein: 8,
      time: "5 min",
      tags: ["Breakfast", "Vegan"],
      image: "https://via.placeholder.com/400x250.png?text=Avocado+Toast",
      ingredients: [
        "2 slices whole-grain bread",
        "1 ripe avocado",
        "Salt",
        "Pepper",
        "Lemon juice",
      ],
      instructions: [
        "Toast the bread slices.",
        "Mash avocado with salt, pepper, and lemon juice.",
        "Spread avocado on toast and serve.",
      ],
    },
    {
      id: 102,
      title: "Greek Yogurt Bowl",
      calories: "250 kcal",
      carbs: 30,
      fats: 5,
      protein: 15,
      time: "4 min",
      tags: ["Breakfast"],
      image: "https://via.placeholder.com/400x250.png?text=Greek+Yogurt+Bowl",
      ingredients: [
        "1 cup Greek yogurt",
        "1 tbsp honey",
        "1/4 cup granola",
        "Fresh berries",
      ],
      instructions: [
        "Spoon Greek yogurt into a bowl.",
        "Top with granola and fresh berries.",
        "Drizzle honey on top before serving.",
      ],
    },
    {
      id: 103,
      title: "Oatmeal with Berries",
      calories: "280 kcal",
      carbs: 50,
      fats: 6,
      protein: 10,
      time: "6 min",
      tags: ["Breakfast", "Vegan"],
      image: "https://via.placeholder.com/400x250.png?text=Oatmeal+with+Berries",
      ingredients: [
        "1/2 cup rolled oats",
        "1 cup almond milk",
        "1/2 cup fresh berries",
        "1 tsp chia seeds",
      ],
      instructions: [
        "Cook oats with almond milk until soft.",
        "Top with berries and chia seeds.",
        "Serve warm.",
      ],
    },
{
  id: 116,
  title: "Banana Pancakes",
  calories: "330 kcal",
  carbs: 45,
  fats: 8,
  protein: 10,
  time: "12 min",
  tags: ["Breakfast", "Sugar Free"],
  image: "https://via.placeholder.com/400x250.png?text=Banana+Pancakes",
  ingredients: [
    "2 ripe bananas",
    "2 eggs",
    "1/2 cup rolled oats",
    "1 tsp cinnamon",
  ],
  instructions: [
    "Blend bananas, eggs, oats, and cinnamon into batter.",
    "Heat a pan and cook pancakes until golden.",
    "Serve with fresh fruit.",
  ],
},
{
  id: 117,
  title: "Peanut Butter Smoothie",
  calories: "280 kcal",
  carbs: 35,
  fats: 12,
  protein: 14,
  time: "5 min",
  tags: ["Breakfast"],
  image: "https://via.placeholder.com/400x250.png?text=Peanut+Butter+Smoothie",
  ingredients: [
    "1 banana",
    "1 tbsp peanut butter",
    "1 cup milk/almond milk",
    "Ice cubes",
  ],
  instructions: [
    "Add all ingredients to blender.",
    "Blend until smooth.",
    "Serve chilled.",
  ],
    },
    {
    id: 118,
    title: "Spinach Egg Muffins",
    calories: "220 kcal",
    carbs: 5,
    fats: 15,
    protein: 18,
    time: "15 min",
    tags: ["Breakfast"],
    image: "https://via.placeholder.com/400x250.png?text=Spinach+Egg+Muffins",
    ingredients: [
        "3 eggs",
        "1/2 cup spinach",
        "1/4 cup cheese",
        "Salt & pepper",
    ],
    instructions: [
        "Whisk eggs, spinach, cheese, salt, and pepper.",
        "Pour into muffin tin.",
        "Bake for 12 minutes at 180°C.",
    ],
    },
  ],

  

  // Lunch
  Lunch: [
    {
      id: 104,
      title: "Grilled Chicken Wrap",
      calories: "420 kcal",
      carbs: 35,
      fats: 12,
      protein: 32,
      time: "15 min",
      tags: ["Lunch"],
      image: "https://via.placeholder.com/400x250.png?text=Grilled+Chicken+Wrap",
      ingredients: [
        "1 whole wheat wrap",
        "100g grilled chicken",
        "Lettuce",
        "Tomato",
        "Light mayo",
      ],
      instructions: [
        "Warm the wrap slightly.",
        "Add grilled chicken, lettuce, and tomato.",
        "Spread mayo and roll tightly.",
      ],
    },
    {
      id: 105,
      title: "Caesar Salad",
      calories: "350 kcal",
      carbs: 20,
      fats: 22,
      protein: 12,
      time: "10 min",
      tags: ["Lunch"],
      image: "https://via.placeholder.com/400x250.png?text=Caesar+Salad",
      ingredients: [
        "2 cups romaine lettuce",
        "Caesar dressing",
        "Croutons",
        "Parmesan cheese",
      ],
      instructions: [
        "Chop romaine lettuce.",
        "Add croutons and parmesan cheese.",
        "Toss with Caesar dressing before serving.",
      ],
    },
    {
      id: 106,
      title: "Quinoa Veggie Bowl",
      calories: "400 kcal",
      carbs: 55,
      fats: 10,
      protein: 15,
      time: "12 min",
      tags: ["Lunch", "Vegan"],
      image: "https://via.placeholder.com/400x250.png?text=Quinoa+Veggie+Bowl",
      ingredients: [
        "1 cup cooked quinoa",
        "1/2 cup roasted veggies",
        "1 tbsp olive oil",
        "Salt & pepper",
      ],
      instructions: [
        "Cook quinoa until fluffy.",
        "Roast or sauté vegetables.",
        "Mix quinoa and veggies, drizzle olive oil, season to taste.",
      ],
    },

    {
        id: 119,
        title: "Turkey Sandwich",
        calories: "390 kcal",
        carbs: 40,
        fats: 12,
        protein: 25,
        time: "7 min",
        tags: ["Lunch"],
        image: "https://via.placeholder.com/400x250.png?text=Turkey+Sandwich",
        ingredients: [
            "2 slices whole grain bread",
            "Turkey breast slices",
            "Lettuce & tomato",
            "Mustard",
        ],
        instructions: [
            "Toast bread lightly.",
            "Layer turkey, lettuce, and tomato.",
            "Spread mustard, cut in half, and serve.",
        ],
        },
        {
        id: 120,
        title: "Falafel Bowl",
        calories: "430 kcal",
        carbs: 50,
        fats: 14,
        protein: 18,
        time: "15 min",
        tags: ["Lunch", "Vegan"],
        image: "https://via.placeholder.com/400x250.png?text=Falafel+Bowl",
        ingredients: [
            "4 falafels",
            "1 cup brown rice",
            "1/2 cup salad",
            "Tahini sauce",
        ],
        instructions: [
            "Warm falafels and rice.",
            "Assemble bowl with salad and falafels.",
            "Drizzle with tahini sauce.",
        ],
        },
        {
        id: 121,
        title: "Stuffed Sweet Potato",
        calories: "370 kcal",
        carbs: 55,
        fats: 8,
        protein: 12,
        time: "20 min",
        tags: ["Lunch", "Vegan"],
        image: "https://via.placeholder.com/400x250.png?text=Stuffed+Sweet+Potato",
        ingredients: [
            "1 baked sweet potato",
            "1/2 cup black beans",
            "Corn",
            "Salsa",
        ],
        instructions: [
            "Bake sweet potato until soft.",
            "Slice open and fill with beans, corn, and salsa.",
            "Serve warm.",
        ],
    },
  ],

  // Dinner
  Dinner: [
    {
      id: 107,
      title: "Baked Salmon",
      calories: "480 kcal",
      carbs: 5,
      fats: 28,
      protein: 45,
      time: "20 min",
      tags: ["Dinner"],
      image: "https://via.placeholder.com/400x250.png?text=Baked+Salmon",
      ingredients: [
        "200g salmon fillet",
        "1 tbsp olive oil",
        "Garlic",
        "Lemon",
        "Salt & pepper",
      ],
      instructions: [
        "Preheat oven to 200°C (400°F).",
        "Season salmon with garlic, lemon, salt, and pepper.",
        "Bake for 15–20 minutes until cooked through.",
      ],
    },
    {
      id: 108,
      title: "Pasta Primavera",
      calories: "450 kcal",
      carbs: 70,
      fats: 12,
      protein: 15,
      time: "18 min",
      tags: ["Dinner", "Vegan"],
      image: "https://via.placeholder.com/400x250.png?text=Pasta+Primavera",
      ingredients: [
        "200g pasta",
        "1 cup mixed vegetables",
        "Olive oil",
        "Garlic",
        "Tomato sauce",
      ],
      instructions: [
        "Boil pasta until al dente.",
        "Sauté vegetables with olive oil and garlic.",
        "Mix pasta with veggies and tomato sauce.",
      ],
    },
    {
      id: 109,
      title: "Stuffed Peppers",
      calories: "430 kcal",
      carbs: 45,
      fats: 15,
      protein: 18,
      time: "25 min",
      tags: ["Dinner", "Vegan"],
      image: "https://via.placeholder.com/400x250.png?text=Stuffed+Peppers",
      ingredients: [
        "3 bell peppers",
        "1 cup cooked rice",
        "1/2 cup beans",
        "Tomato sauce",
        "Herbs & spices",
      ],
      instructions: [
        "Preheat oven to 180°C (350°F).",
        "Cut and hollow peppers.",
        "Mix rice, beans, and sauce, then stuff into peppers.",
        "Bake for 20 minutes.",
      ],
    },

    {
    id: 122,
    title: "Chicken Stir Fry",
    calories: "410 kcal",
    carbs: 40,
    fats: 12,
    protein: 30,
    time: "14 min",
    tags: ["Dinner"],
    image: "https://via.placeholder.com/400x250.png?text=Chicken+Stir+Fry",
    ingredients: [
        "150g chicken breast",
        "1 cup mixed vegetables",
        "2 tbsp soy sauce",
        "1 tbsp olive oil",
    ],
    instructions: [
        "Heat oil in a pan.",
        "Cook chicken until golden.",
        "Add vegetables and soy sauce, stir fry 5 minutes.",
    ],
    },
    {
    id: 123,
    title: "Veggie Curry",
    calories: "420 kcal",
    carbs: 60,
    fats: 12,
    protein: 12,
    time: "22 min",
    tags: ["Dinner", "Vegan"],
    image: "https://via.placeholder.com/400x250.png?text=Veggie+Curry",
    ingredients: [
        "1 cup mixed vegetables",
        "1/2 cup coconut milk",
        "Curry paste",
        "Spices",
    ],
    instructions: [
        "Heat curry paste in pan.",
        "Add vegetables and coconut milk.",
        "Simmer for 15 minutes and serve with rice.",
    ],
    },
    {
    id: 124,
    title: "Shrimp Tacos",
    calories: "360 kcal",
    carbs: 35,
    fats: 10,
    protein: 25,
    time: "12 min",
    tags: ["Dinner"],
    image: "https://via.placeholder.com/400x250.png?text=Shrimp+Tacos",
    ingredients: [
        "6 shrimp",
        "2 small tortillas",
        "Cabbage slaw",
        "Salsa",
    ],
    instructions: [
        "Cook shrimp with spices.",
        "Warm tortillas.",
        "Assemble tacos with shrimp, slaw, and salsa.",
    ],
    },
  ],

  // Vegan
  Vegan: [
    {
      id: 110,
      title: "Tofu Stir Fry",
      calories: "380 kcal",
      carbs: 40,
      fats: 16,
      protein: 20,
      time: "15 min",
      tags: ["Vegan", "Dinner"],
      image: "https://via.placeholder.com/400x250.png?text=Tofu+Stir+Fry",
      ingredients: [
        "200g tofu (cubed)",
        "1 cup mixed vegetables",
        "2 tbsp soy sauce",
        "1 tbsp sesame oil",
        "Garlic & ginger",
      ],
      instructions: [
        "Heat sesame oil in a pan.",
        "Add garlic, ginger, tofu, and stir-fry until golden.",
        "Add vegetables and soy sauce. Cook 5 more minutes.",
      ],
    },
    {
      id: 111,
      title: "Lentil Soup",
      calories: "300 kcal",
      carbs: 45,
      fats: 5,
      protein: 18,
      time: "20 min",
      tags: ["Vegan", "Lunch"],
      image: "https://via.placeholder.com/400x250.png?text=Lentil+Soup",
      ingredients: [
        "1 cup red lentils",
        "1 onion (chopped)",
        "2 carrots (diced)",
        "Vegetable broth",
        "Spices (cumin, paprika, salt)",
      ],
      instructions: [
        "Sauté onion and carrots in a pot.",
        "Add lentils and vegetable broth.",
        "Simmer until lentils are soft. Season with spices.",
      ],
    },
    {
      id: 112,
      title: "Vegan Burger",
      calories: "410 kcal",
      carbs: 50,
      fats: 12,
      protein: 20,
      time: "18 min",
      tags: ["Vegan", "Dinner"],
      image: "https://via.placeholder.com/400x250.png?text=Vegan+Burger",
      ingredients: [
        "1 vegan patty",
        "1 whole wheat bun",
        "Lettuce & tomato",
        "Vegan mayo",
        "Pickles",
      ],
      instructions: [
        "Cook vegan patty in a pan or grill.",
        "Toast the bun lightly.",
        "Assemble with lettuce, tomato, mayo, and pickles.",
      ],
    },

    {id: 125,
  title: "Chickpea Salad",
  calories: "350 kcal",
  carbs: 40,
  fats: 10,
  protein: 15,
  time: "10 min",
  tags: ["Vegan", "Lunch"],
  image: "https://via.placeholder.com/400x250.png?text=Chickpea+Salad",
  ingredients: [
    "1 cup chickpeas",
    "Cucumber",
    "Tomato",
    "Lemon dressing",
  ],
  instructions: [
    "Chop vegetables.",
    "Mix chickpeas with cucumber, tomato, and dressing.",
    "Serve fresh.",
  ],
},
{
  id: 126,
  title: "Vegan Pasta Salad",
  calories: "390 kcal",
  carbs: 60,
  fats: 12,
  protein: 14,
  time: "15 min",
  tags: ["Vegan", "Lunch"],
  image: "https://via.placeholder.com/400x250.png?text=Vegan+Pasta+Salad",
  ingredients: [
    "200g pasta",
    "Olives",
    "Cherry tomatoes",
    "Vegan dressing",
  ],
  instructions: [
    "Cook pasta until al dente.",
    "Mix with olives and tomatoes.",
    "Toss with vegan dressing.",
  ],
},
{
  id: 127,
  title: "Stuffed Zucchini",
  calories: "320 kcal",
  carbs: 35,
  fats: 9,
  protein: 12,
  time: "18 min",
  tags: ["Vegan", "Dinner"],
  image: "https://via.placeholder.com/400x250.png?text=Stuffed+Zucchini",
  ingredients: [
    "2 zucchinis",
    "1/2 cup quinoa",
    "Tomato sauce",
    "Herbs",
  ],
  instructions: [
    "Hollow out zucchinis.",
    "Cook quinoa and mix with sauce.",
    "Stuff zucchinis and bake 15 minutes.",
     ],
    },
  ],

  // Sugar Free
  "Sugar Free": [
    {
      id: 113,
      title: "Chia Seed Pudding",
      calories: "200 kcal",
      carbs: 25,
      fats: 8,
      protein: 6,
      time: "10 min",
      tags: ["Breakfast", "Sugar Free"],
      image: "https://via.placeholder.com/400x250.png?text=Chia+Seed+Pudding",
      ingredients: [
        "3 tbsp chia seeds",
        "1 cup almond milk",
        "Vanilla extract",
        "Fresh fruit topping",
      ],
      instructions: [
        "Mix chia seeds with almond milk and vanilla.",
        "Refrigerate overnight until pudding-like.",
        "Serve with fresh fruit on top.",
      ],
    },
    {
      id: 114,
      title: "Sugar-Free Brownies",
      calories: "250 kcal",
      carbs: 30,
      fats: 10,
      protein: 5,
      time: "25 min",
      tags: ["Dessert", "Sugar Free"],
      image: "https://via.placeholder.com/400x250.png?text=Sugar+Free+Brownies",
      ingredients: [
        "1 cup almond flour",
        "1/2 cup cocoa powder",
        "Sugar substitute",
        "2 eggs",
        "1/4 cup coconut oil",
      ],
      instructions: [
        "Preheat oven to 180°C (350°F).",
        "Mix all ingredients until smooth.",
        "Pour batter into a pan and bake for 20 minutes.",
      ],
    },
    {
      id: 115,
      title: "Fruit Salad",
      calories: "150 kcal",
      carbs: 35,
      fats: 1,
      protein: 2,
      time: "5 min",
      tags: ["Breakfast", "Sugar Free", "Vegan"],
      image: "https://via.placeholder.com/400x250.png?text=Fruit+Salad",
      ingredients: [
        "1 cup mixed fruit (apple, banana, berries, melon)",
        "1 tsp lemon juice",
        "Fresh mint leaves (optional)",
      ],
      instructions: [
        "Chop all fruits into bite-sized pieces.",
        "Drizzle with lemon juice.",
        "Garnish with mint and serve fresh.",
      ],
    },


    {
  id: 128,
  title: "Apple Cinnamon Oats",
  calories: "260 kcal",
  carbs: 48,
  fats: 4,
  protein: 7,
  time: "7 min",
  tags: ["Breakfast", "Sugar Free"],
  image: "https://via.placeholder.com/400x250.png?text=Apple+Cinnamon+Oats",
  ingredients: [
    "1/2 cup oats",
    "1 cup milk/almond milk",
    "1 apple (chopped)",
    "Cinnamon",
  ],
  instructions: [
    "Cook oats with milk.",
    "Stir in apple and cinnamon.",
    "Serve warm.",
  ],
    },
    {
    id: 129,
    title: "Coconut Energy Balls",
    calories: "210 kcal",
    carbs: 20,
    fats: 12,
    protein: 6,
    time: "6 min",
    tags: ["Snack", "Sugar Free", "Vegan"],
    image: "https://via.placeholder.com/400x250.png?text=Coconut+Energy+Balls",
    ingredients: [
        "1 cup dates",
        "1/2 cup shredded coconut",
        "1/4 cup oats",
        "1 tbsp almond butter",
    ],
    instructions: [
        "Blend all ingredients until sticky.",
        "Roll into balls and coat with coconut.",
        "Chill before serving.",
    ],
    },
    {
    id: 130,
    title: "Zucchini Brownies",
    calories: "240 kcal",
    carbs: 28,
    fats: 9,
    protein: 5,
    time: "25 min",
    tags: ["Dessert", "Sugar Free"],
    image: "https://via.placeholder.com/400x250.png?text=Zucchini+Brownies",
    ingredients: [
        "1 cup grated zucchini",
        "1/2 cup almond flour",
        "1/4 cup cocoa powder",
        "Sugar substitute",
    ],
    instructions: [
        "Mix zucchini with other ingredients.",
        "Pour batter into tray.",
        "Bake for 20 minutes at 180°C.",
    ],
    },
  ],
  //Restaurant
  "Suggested Restaurant": [
    { id: 201, title: "Healthy Bites", price: "20-25", rating: 4.5, distance: "1.2 km" },
    { id: 202, title: "Green Leaf Cafe", price: "$10-15", rating: 4.7, distance: "2.0 km" },
    { id: 203, title: "Vegan Delight", price: "$15-20", rating: 4.3, distance: "800 m" },
    { id: 204, title: "Fit Fuel Diner", price: "$25-30", rating: 4.6, distance: "3.5 km" },
  ],

  
};
export default recipesData;
